export const SOURCE = {
  "label": "Think 第二版 · Level 1 · Unit 1 样章精选（36 词）",
  "url": "https://oxico.sk/lg/aj/assets/ukazky/think_2nd_1.pdf",
  "note": "已核对公开样章 Unit 1 第 12—15 页中的 36 个精选词条，不代表完整单元或全册词表。例句和中文释义为自行编写。"
};
export const UNITS = [
  {
    "id": "u1",
    "name": "Unit 1",
    "title": "Having a good time",
    "zh": "享受美好时光",
    "topics": "爱好；have 的搭配",
    "page": 12,
    "available": true
  }
];
export const WORDS = [
  {
    "id": "u1-1",
    "unit": "u1",
    "en": "hobby",
    "pos": "n.",
    "zh": "业余爱好",
    "example": "Drawing is my favourite hobby.",
    "translation": "画画是我最喜欢的业余爱好。",
    "sourcePage": 13,
    "sourceSection": "reading",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-2",
    "unit": "u1",
    "en": "instrument",
    "pos": "n.",
    "zh": "乐器",
    "example": "She plays an instrument in the school band.",
    "translation": "她在学校乐队里演奏一种乐器。",
    "sourcePage": 14,
    "sourceSection": "vocabulary",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-3",
    "unit": "u1",
    "en": "club",
    "pos": "n.",
    "zh": "俱乐部；社团",
    "example": "We meet at the chess club on Fridays.",
    "translation": "我们每周五在国际象棋社团见面。",
    "sourcePage": 14,
    "sourceSection": "vocabulary",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-4",
    "unit": "u1",
    "en": "blog",
    "pos": "n.",
    "zh": "博客",
    "example": "I write a blog about my little garden.",
    "translation": "我写一个关于我的小花园的博客。",
    "sourcePage": 14,
    "sourceSection": "vocabulary",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-5",
    "unit": "u1",
    "en": "photo",
    "pos": "n.",
    "zh": "照片",
    "example": "This photo shows our class at the zoo.",
    "translation": "这张照片拍的是我们班在动物园的情景。",
    "sourcePage": 14,
    "sourceSection": "vocabulary",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-6",
    "unit": "u1",
    "en": "pet",
    "pos": "n.",
    "zh": "宠物",
    "example": "My pet rabbit likes carrots.",
    "translation": "我的宠物兔子喜欢胡萝卜。",
    "sourcePage": 14,
    "sourceSection": "vocabulary",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-7",
    "unit": "u1",
    "en": "collect",
    "pos": "v.",
    "zh": "收集",
    "example": "I collect postcards from different cities.",
    "translation": "我收集不同城市的明信片。",
    "sourcePage": 14,
    "sourceSection": "vocabulary",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-8",
    "unit": "u1",
    "en": "keep",
    "pos": "v.",
    "zh": "饲养；养",
    "example": "We keep a small fish at home.",
    "translation": "我们在家里养一条小鱼。",
    "sourcePage": 14,
    "sourceSection": "vocabulary",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-9",
    "unit": "u1",
    "en": "play",
    "pos": "v.",
    "zh": "演奏；玩",
    "example": "Can you play the guitar?",
    "translation": "你会弹吉他吗？",
    "sourcePage": 14,
    "sourceSection": "vocabulary",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-10",
    "unit": "u1",
    "en": "take",
    "pos": "v.",
    "zh": "拍摄；拿取",
    "example": "Let us take a photo by the lake.",
    "translation": "我们在湖边拍张照片吧。",
    "sourcePage": 14,
    "sourceSection": "vocabulary",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-11",
    "unit": "u1",
    "en": "write",
    "pos": "v.",
    "zh": "写",
    "example": "I write a short story every week.",
    "translation": "我每周写一个小故事。",
    "sourcePage": 14,
    "sourceSection": "vocabulary",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-12",
    "unit": "u1",
    "en": "practise",
    "pos": "v.",
    "zh": "练习",
    "example": "I practise the piano after school.",
    "translation": "我放学后练习钢琴。",
    "sourcePage": 15,
    "sourceSection": "wordwise",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-13",
    "unit": "u1",
    "en": "judo",
    "pos": "n.",
    "zh": "柔道",
    "example": "My brother has a judo lesson today.",
    "translation": "我哥哥今天有一节柔道课。",
    "sourcePage": 15,
    "sourceSection": "listening_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-14",
    "unit": "u1",
    "en": "crossword",
    "pos": "n.",
    "zh": "填字游戏",
    "example": "We do a crossword on the train.",
    "translation": "我们在火车上做填字游戏。",
    "sourcePage": 15,
    "sourceSection": "listening_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-15",
    "unit": "u1",
    "en": "stamp",
    "pos": "n.",
    "zh": "邮票",
    "example": "There is a bird on this stamp.",
    "translation": "这张邮票上有一只鸟。",
    "sourcePage": 15,
    "sourceSection": "vocabulary_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-16",
    "unit": "u1",
    "en": "brain",
    "pos": "n.",
    "zh": "大脑",
    "example": "Sleep is good for your brain.",
    "translation": "睡眠对你的大脑有益。",
    "sourcePage": 15,
    "sourceSection": "listening_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-17",
    "unit": "u1",
    "en": "strength",
    "pos": "n.",
    "zh": "力量；体力",
    "example": "Swimming helps me build strength.",
    "translation": "游泳帮助我增强体力。",
    "sourcePage": 15,
    "sourceSection": "listening_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-18",
    "unit": "u1",
    "en": "puzzle",
    "pos": "n.",
    "zh": "谜题；智力游戏",
    "example": "This number puzzle is fun.",
    "translation": "这个数字谜题很有趣。",
    "sourcePage": 13,
    "sourceSection": "reading",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-19",
    "unit": "u1",
    "en": "piano",
    "pos": "n.",
    "zh": "钢琴",
    "example": "Our music room has a new piano.",
    "translation": "我们的音乐教室有一架新钢琴。",
    "sourcePage": 15,
    "sourceSection": "vocabulary_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-20",
    "unit": "u1",
    "en": "talent",
    "pos": "n.",
    "zh": "天赋；才能",
    "example": "Everyone has a different talent.",
    "translation": "每个人都有不同的才能。",
    "sourcePage": 15,
    "sourceSection": "vocabulary_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-21",
    "unit": "u1",
    "en": "rest",
    "pos": "n.",
    "zh": "休息",
    "example": "Have a rest after the long walk.",
    "translation": "长时间步行后休息一下吧。",
    "sourcePage": 15,
    "sourceSection": "wordwise",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-22",
    "unit": "u1",
    "en": "homework",
    "pos": "n.",
    "zh": "家庭作业",
    "example": "I finish my homework before dinner.",
    "translation": "我在晚饭前完成家庭作业。",
    "sourcePage": 12,
    "sourceSection": "reading_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-23",
    "unit": "u1",
    "en": "housework",
    "pos": "n.",
    "zh": "家务",
    "example": "We share the housework at weekends.",
    "translation": "我们在周末分担家务。",
    "sourcePage": 12,
    "sourceSection": "reading_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-24",
    "unit": "u1",
    "en": "exercise",
    "pos": "n.",
    "zh": "锻炼；运动",
    "example": "A short walk is good exercise.",
    "translation": "短时间散步是一种很好的锻炼。",
    "sourcePage": 12,
    "sourceSection": "reading_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-25",
    "unit": "u1",
    "en": "dance",
    "pos": "v.",
    "zh": "跳舞",
    "example": "They dance to their favourite song.",
    "translation": "他们随着最喜欢的歌曲跳舞。",
    "sourcePage": 12,
    "sourceSection": "reading_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-26",
    "unit": "u1",
    "en": "sing",
    "pos": "v.",
    "zh": "唱歌",
    "example": "We sing together in music class.",
    "translation": "我们在音乐课上一起唱歌。",
    "sourcePage": 12,
    "sourceSection": "reading_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-27",
    "unit": "u1",
    "en": "cook",
    "pos": "v.",
    "zh": "烹饪；做饭",
    "example": "I help my dad cook lunch.",
    "translation": "我帮助爸爸做午饭。",
    "sourcePage": 14,
    "sourceSection": "grammar_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-28",
    "unit": "u1",
    "en": "read",
    "pos": "v.",
    "zh": "阅读",
    "example": "I read a book before bed.",
    "translation": "我睡觉前读一本书。",
    "sourcePage": 12,
    "sourceSection": "reading_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-29",
    "unit": "u1",
    "en": "sleep",
    "pos": "v.",
    "zh": "睡觉",
    "example": "I sleep for nine hours each night.",
    "translation": "我每晚睡九个小时。",
    "sourcePage": 13,
    "sourceSection": "reading",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-30",
    "unit": "u1",
    "en": "laugh",
    "pos": "v.",
    "zh": "笑",
    "example": "That funny story makes us laugh.",
    "translation": "那个有趣的故事让我们笑了。",
    "sourcePage": 13,
    "sourceSection": "reading",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-31",
    "unit": "u1",
    "en": "healthy",
    "pos": "adj.",
    "zh": "健康的",
    "example": "Fruit and exercise help us stay healthy.",
    "translation": "水果和运动帮助我们保持健康。",
    "sourcePage": 13,
    "sourceSection": "reading",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-32",
    "unit": "u1",
    "en": "busy",
    "pos": "adj.",
    "zh": "忙碌的",
    "example": "Mum is busy in the kitchen.",
    "translation": "妈妈正在厨房里忙碌。",
    "sourcePage": 13,
    "sourceSection": "reading",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-33",
    "unit": "u1",
    "en": "enjoy",
    "pos": "v.",
    "zh": "喜欢；享受",
    "example": "I enjoy making things with my friends.",
    "translation": "我喜欢和朋友们一起动手做东西。",
    "sourcePage": 13,
    "sourceSection": "reading",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-34",
    "unit": "u1",
    "en": "boring",
    "pos": "adj.",
    "zh": "无聊的",
    "example": "Waiting in a long line is boring.",
    "translation": "排很长的队很无聊。",
    "sourcePage": 12,
    "sourceSection": "reading_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-35",
    "unit": "u1",
    "en": "difficult",
    "pos": "adj.",
    "zh": "困难的",
    "example": "The first question is difficult for me.",
    "translation": "第一道题对我来说很难。",
    "sourcePage": 12,
    "sourceSection": "reading_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  },
  {
    "id": "u1-36",
    "unit": "u1",
    "en": "relax",
    "pos": "v.",
    "zh": "放松",
    "example": "I listen to quiet music to relax.",
    "translation": "我听舒缓的音乐来放松。",
    "sourcePage": 15,
    "sourceSection": "vocabulary_activity",
    "normalization": "dictionary_headword; some source forms are plural or -ing"
  }
];
